### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by lisaratner** [codeforamerica/bizport#238]
Add that copy to the footer

**Comment by rossettistone** [comment]
Where in the footer should this go? Does this need to link to  or name particular creator profiles in the Noun Project site to meet our reporting requirements?

**Comment by lisaratner** [comment]
Just generally to the NounProject for now
Also please add the Github link to the footer

**Comment by rossettistone** [comment]
NounProject link: https://thenounproject.com/
GitHub link: github.com/codeforamerica/bizport

**Comment by lisaratner** [comment]
"Designed and Built by Code for America and Long Beach i-team
Icons by TheNounProject.com
Open Source code on Github (link)"

**Comment by lxchavez** [comment]
Changes have been approved and is now live
