### ISSUE TITLE
Transition SAAS to i-team/John

### ISSUE THREAD

**Issue by heidiwiersma** [codeforamerica/bizport#254]
Change account info to i-team@longbeach.gov email and add John's Credit card info.

**Comment by rossettistone** [comment]
Just did this for Keen.io and Google Analytics. GA doesn't support non-Google email addresses, but I've given access to Eric, and he or I can give access to anyone else that needs it for continuity.

**Comment by heidiwiersma** [comment]
Eric Deck?

**Comment by rossettistone** [comment]
Romero. Sorry, that was unclear.

**Comment by rossettistone** [comment]
@heidiwiersma Anything else you need from us on this one? I know you've been working through the Chart of Accounts google doc, and wanted to make sure we didn't overlook anything (that we know of!) on there.
