### ISSUE TITLE
Competitive Audit continued

### ISSUE THREAD

**Issue by lisaratner** [codeforamerica/bizport#294]
Efrem: Mayor Nutter suggested we take a look at Philly’s site for business services: https://business.phila.gov/

I really like how there are 3 options on the homepage. It feels less overwhelming and cuts down on the initial content.

Check out Memphis’s version of a checklist by clicking the “start your wizard now” http://www.smartstartmem.com/

[12:15]  
^ @lisa @rossettistone this is actually pretty cool. It gives you an actual list of everything you need: http://www.smartstartmem.com/checklist/390-786-533

http://technical.ly/dc/2016/06/29/1776-startup-federation-union-platform/

**Comment by lisa** [comment]
@lisaratner Hi other Lisa! :) I'm not sure you meant to tag me specifically.
