### ISSUE TITLE
Fix Checklist Wording

### ISSUE THREAD

**Issue by lisaratner** [codeforamerica/bizport#301]
These got out of order in that some of the checklist items are on the wrong page.

**Comment by lisaratner** [comment]
Hey Mark, I've been trying to update the checklist items. When I go to delete and item this is the error message I get:

"We're sorry, but something went wrong.
If you are the application owner check the logs for more information."

Can I delete checklist items from my account?

**Comment by rossettistone** [comment]
Looks like the problem is that it isn't letting you delete checklist items that some users have already checked off. I'll work on a fix ASAP.

**Comment by rossettistone** [comment]
Should be resolved now. Let me know if you still have trouble.

**Comment by rossettistone** [comment]
We should schedule an hour this week to work with Eric and/or Heidi on updating this. Would be best if they have the know-how to do so in future.

**Comment by lisaratner** [comment]
SMEs will edit these on the content doc with @rossettistone thursday

**Comment by lisaratner** [comment]
DONE
zoning
plan check
permit
inspections
determine
apply
manage
