### ISSUE TITLE
Make the "Sources and Uses of Funds" table responsive/mobile friendly

### ISSUE THREAD

**Issue by lxchavez** [codeforamerica/bizport#363]
See the table under the "Sources and Uses of Funds" section of the [Financial Plan page](http://bizport.longbeach.gov/plan/financial-plan).

**Comment by lxchavez** [comment]
This table was created using Markdown. Instead, the table might have to be created with appropriate  Foundation markup and CSS classes.

This might be worth looking into: http://zurb.com/playground/responsive-tables

Also, it might be a good idea to create a CMS "Tag" Content item for tables in general.

**Comment by terabytes** [comment]
Foundation v6 has support for responsive/mobile-friendly tables with its addition of responsive modifiers. I updated the content in the CMS to use full HTML markup and appropriate modifiers so the table is now responsive.
