### ISSUE TITLE
Flair ideas for completion

### ISSUE THREAD

**Issue by lisaratner** [codeforamerica/bizport#77]

**Comment by rossettistone** [comment]
Can you elaborate on this? I'm not sure what "Flare" refers to.

**Comment by lisaratner** [comment]
No idea... Ha

On Monday, May 9, 2016, Mark Rossetti <notifications@github.com> wrote:

> Closed #77 <https://github.com/rossettistone/bizport/issues/77>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/rossettistone/bizport/issues/77#event-654809779>
>


-- 
Lisa Ratner
User Experience Designer
*UX-by-Lisa.com <http://UX-by-Lisa.com>*
LisaARatner@gmail.com
(650) 207-3682

**Comment by rogerhoward** [comment]
https://www.youtube.com/watch?v=KJtrLKGZZFg

Sorry, I'm lurking :)

**Comment by rossettistone** [comment]
👍 👍 👍
